# Clippy configuration
# This ensures consistent linting across different environments

# Maximum allowed cognitive complexity of a function
cognitive-complexity-threshold = 30

# Maximum number of lines in a function
too-many-lines-threshold = 100

# Maximum number of arguments in a function
too-many-arguments-threshold = 7

# Enforce MSRV (Minimum Supported Rust Version)
msrv = "1.86.0"
