services:
  estuary:
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_TYPE=${DATABASE_TYPE:-memory}
      - CONVEX_DEPLOYMENT_URL=${CONVEX_DEPLOYMENT_URL}
      - RUST_LOG=${RUST_LOG:-estuary=info,tower_http=warn}
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - RATE_LIMIT_WINDOW_SECONDS=${RATE_LIMIT_WINDOW_SECONDS:-60}
      - AUTH_ENABLED=${AUTH_ENABLED:-false}
      - AUTH_JWKS_URLS=${AUTH_JWKS_URLS}
      - AUTH_AUDIENCE=${AUTH_AUDIENCE}
      - AUTH_ISSUER=${AUTH_ISSUER}
      - SECURITY_STRICT_MODE=${SECURITY_STRICT_MODE:-false}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
