# Production overrides - use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
services:
  ferrous:
    image: ${DOCKER_REGISTRY:-docker.io}/ferrous:${VERSION:-latest}
    environment:
      - APP_PROFILE=production
      - RUST_LOG=ferrous=info,tower_http=warn
      - RATE_LIMIT_MAX_REQUESTS=100
      - AUTH_ENABLED=true
      - SECURITY_STRICT_MODE=true
    restart: always
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
