blank_issues_enabled: false
contact_links:
  - name: Community Discord
    url: https://discord.gg/your-discord
    about: Please ask and answer questions here (update this URL when Discord is available)
  - name: Security Issues
    url: mailto:security@example.com
    about: Please report security vulnerabilities via email (update this email)
