# Cargo configuration for consistent builds

[build]
# Number of parallel jobs, defaults to # of CPUs
# jobs = 1

[target.'cfg(all())']
# Ensure consistent behavior across platforms
rustflags = ["-D", "warnings"]

# Lint configuration
[lints.rust]
unsafe_code = "warn"
missing_docs = "allow"

[lints.clippy]
# Deny specific lints that might be warnings in some versions
uninlined_format_args = "deny"
# Add other clippy lints you want to enforce
pedantic = "warn"
nursery = "warn"
# Allow some pedantic lints that might be too strict
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"

[profile.dev]
# Faster builds in development
opt-level = 0
debug = true

[profile.release]
# Optimize for size in release builds
opt-level = 3
lto = true
codegen-units = 1
