name: Welcome New Contributors

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Welcome to Estuary, @${{ github.actor }}!

            Thank you for opening your first issue! We appreciate your interest in the project.

            A maintainer will review your issue soon. In the meantime:
            - Please ensure you've filled out the issue template completely
            - Check if there are any similar existing issues
            - Feel free to join our community discussions

            If you have any questions, don't hesitate to ask!

          pr-message: |
            🎉 Welcome to Estuary, @${{ github.actor }}!

            Thank you for your first contribution! We're excited to review your pull request.

            Please ensure:
            - [ ] All tests pass (`cargo test`)
            - [ ] Code is formatted (`cargo fmt`)
            - [ ] No clippy warnings (`cargo clippy`)
            - [ ] Documentation is updated if needed

            A maintainer will review your PR soon. Thank you for helping make Estuary better!

            If this is your first time contributing to open source, congratulations! 🌟
